[package]
name = "cphp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cphp"
path = "src/main.rs"

[[bin]]
name = "vm"
path = "src/vm.rs"

[[bin]]
name = "encoder"
path = "src/encoder.rs"

[dependencies]
